<div id="bass_pickups" class="bass-pickups-page container-fluid page">
    <div class="row">
        <!--( a ) Portfolio Page Fixed Image Portion -->

        <div class="image-container col-md-3 col-sm-12">
            <div class="mask">
            </div>
            <div class="main-heading">
                <h1>Bass Pickups</h1>
            </div>
        </div>
        <div class="content-container col-md-9 col-sm-12">
            <div class="clearfix full-height">
             <div class="row">

                  <?php include_once ('./sets/jbass.phtml')?>
                 <?php include_once ('./sets/pbass.phtml')?>

                </div>
            </div>
            <?php include 'footer.phtml'; ?>
        </div>
    </div>
</div>


