<div id="bass_pickups" class="bass-pickups-page container-fluid page">
    <div class="row">
        <!--( a ) Portfolio Page Fixed Image Portion -->

        <div class="image-container col-md-3 col-sm-12">
            <div class="mask">
            </div>
            <div class="main-heading">
                <h1>Bass Pickups</h1>
            </div>
        </div>

        <!--( b ) Portfolio Page Content -->

        <div class="content-container col-md-9 col-sm-12">

            <!--( A ) Portfolio -->

            <div class="clearfix">
                <h2 class="small-heading">BASS PICKUPS</h2>
                <div class="row">
                    <div class="col-md-10 col-md-offset-1 col-sm-12">
                        <div class="row">

                            <div class="col-md-6 col-sm-12">
                                <div class="faq-desc-item">
                                    <div class="flip-container text-center">
                                        <div class="flipper" >
                                            <div class="front-bass">
                                                <h5><a href="#p-bass">P-Bass<sup>&trade;</sup> Style</a></h5>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-6 col-sm-12">
                                <div class="faq-desc-item">
                                    <div class="flip-container text-center">
                                        <div class="flipper">
                                            <div class="front-bass">
                                                <h5><a href="#j-bass">J-Bass<sup>&trade;</sup> Stytle</a></h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>



                        </div>
                    </div>
                </div>
            </div>


            <?php include_once ('./sets/jbass.phtml')?>

            <?php include_once ('./sets/pbass.phtml')?>

            <!-- end: pricing section -->



            <!-- end: valuable clients -->




            <!-- Footer -->

            <?php require_once 'footer.phtml'; ?>

        </div>
    </div>
</div>