<div id="bass_pickups" class="portfolio-page container-fluid page">

    <div class="row">

        <!--( a ) Portfolio Page Fixed Image Portion -->

        <div class="image-container col-md-3 col-sm-12">
            <div class="mask">
            </div>
            <div class="main-heading">
                <h1>Portfolio</h1>
            </div>
        </div>

        <!--( b ) Portfolio Page Content -->

        <div class="content-container col-md-9 col-sm-12">

            <!--( A ) Portfolio -->

            <div class="portfolio clearfix full-height">
                <h2 class="small-heading">PORTFOLIO</h2>

                <div class="row">
                    <div class="col-md-10 col-md-offset-1 col-xs-10 col-xs-offset-1">
                        <div class="project-container">
                            <div class="row">
                                <div class="project-controls">
                                    <button class="filter" data-filter="all">All</button>
                                    <button class="filter" data-filter=".graphic-design">Graphic Design</button>
                                    <button class="filter" data-filter=".web-design">Web Designs</button>
                                    <button class="filter" data-filter=".app-development">App Development</button>
                                </div>

                                <!-- Portfolio Control Buttons [ END ] -->

                                <div id="projects" class="projet-items clearfix">

                                    <!-- Portfolio Image -->

                                    <div class="col-lg-4 col-md-6 col-sm-4 col-xs-6 mix graphic-design">
                                        <div class="project">
                                            <img src="assets/img/portfolio/thumbs/image_1.jpg" alt="">
                                            <div class="ovrly">
                                            </div>
                                            <div class="buttons">
                                                <a href="#" class="fa fa-link"></a>
                                                <a href="#portfolio-1" class="fa fa-search show-popup"></a>
                                            </div>
                                        </div>
                                    </div>

                                    <!-- Popup Content -->

                                    <div class="pop-up-box" id="portfolio-1">
                                        <img alt="" src="assets/img/portfolio/image_1.jpg" class=" hidden-xs">
                                        <div class="popup-content">
                                            <h3>PROJECT NAME</h3>
                                            <p>
                                                Quisque in tempor sapien, et cursus neque. Nunc pulvinar diam ac dapibus
                                                mollis. Etiam id iaculis lorem. Donec bibendum volutpat ante, eu
                                                consequat nisi suscipit at. Etiam interdum augue dolor, id auctor felis
                                                volutpat sed. Phasellus id ex ultrices, tempus leo eget, volutpat diam.
                                                In sit amet magna faucibus, molestie nisi in, hendrerit libero. Morbi
                                                auctor velit sagittis, elementum lorem eget, imperdiet nisl.
                                            </p>
                                            <a href="#">PREVIEW</a>
                                        </div>
                                    </div>

                                    <!-- Single Portfolio Item [ END ] -->


                                    <!-- Portfolio Image -->

                                    <div class="col-lg-4 col-md-6 col-sm-4 col-xs-6 mix web-design">
                                        <div class="project">
                                            <img src="assets/img/portfolio/thumbs/image_2.jpg" alt="">
                                            <div class="ovrly">
                                            </div>
                                            <div class="buttons">
                                                <a href="#" class="fa fa-link"></a>
                                                <a href="#portfolio-2" class="fa fa-search show-popup"></a>
                                            </div>
                                        </div>
                                    </div>

                                    <!-- Popup Content -->

                                    <div class="pop-up-box" id="portfolio-2">
                                        <img alt="" src="assets/img/portfolio/image_2.jpg" class=" hidden-xs">
                                        <div class="popup-content">
                                            <h3>PROJECT NAME</h3>
                                            <p>
                                                Quisque in tempor sapien, et cursus neque. Nunc pulvinar diam ac dapibus
                                                mollis. Etiam id iaculis lorem. Donec bibendum volutpat ante, eu
                                                consequat nisi suscipit at. Etiam interdum augue dolor, id auctor felis
                                                volutpat sed. Phasellus id ex ultrices, tempus leo eget, volutpat diam.
                                                In sit amet magna faucibus, molestie nisi in, hendrerit libero. Morbi
                                                auctor velit sagittis, elementum lorem eget, imperdiet nisl.
                                            </p>
                                            <a href="#">PREVIEW</a>
                                        </div>
                                    </div>

                                    <!-- Single Portfolio Item [ END ] -->


                                    <!-- Portfolio Image -->

                                    <div class="col-lg-4 col-md-6 col-sm-4 col-xs-6 mix app-development">
                                        <div class="project">
                                            <img src="assets/img/portfolio/thumbs/image_3.jpg" alt="">
                                            <div class="ovrly">
                                            </div>
                                            <div class="buttons">
                                                <a href="#" class="fa fa-link"></a>
                                                <a href="#portfolio-3" class="fa fa-search show-popup"></a>
                                            </div>
                                        </div>
                                    </div>

                                    <!-- Popup Content -->

                                    <div class="pop-up-box" id="portfolio-3">
                                        <img alt="" src="assets/img/portfolio/image_3.jpg" class=" hidden-xs">
                                        <div class="popup-content">
                                            <h3>PROJECT NAME</h3>
                                            <p>
                                                Quisque in tempor sapien, et cursus neque. Nunc pulvinar diam ac dapibus
                                                mollis. Etiam id iaculis lorem. Donec bibendum volutpat ante, eu
                                                consequat nisi suscipit at. Etiam interdum augue dolor, id auctor felis
                                                volutpat sed. Phasellus id ex ultrices, tempus leo eget, volutpat diam.
                                                In sit amet magna faucibus, molestie nisi in, hendrerit libero. Morbi
                                                auctor velit sagittis, elementum lorem eget, imperdiet nisl.
                                            </p>
                                            <a href="#">PREVIEW</a>
                                        </div>
                                    </div>

                                    <!-- Single Portfolio Item [ END ] -->


                                    <!-- Portfolio Image -->

                                    <div class="col-lg-4 col-md-6 col-sm-4 col-xs-6 mix graphic-design">
                                        <div class="project">
                                            <img src="assets/img/portfolio/thumbs/image_4.jpg" alt="">
                                            <div class="ovrly">
                                            </div>
                                            <div class="buttons">
                                                <a href="#" class="fa fa-link"></a>
                                                <a href="#portfolio-4" class="fa fa-search show-popup"></a>
                                            </div>
                                        </div>
                                    </div>

                                    <!-- Popup Content -->

                                    <div class="pop-up-box" id="portfolio-4">
                                        <img alt="" src="assets/img/portfolio/image_4.jpg" class=" hidden-xs">
                                        <div class="popup-content">
                                            <h3>PROJECT NAME</h3>
                                            <p>
                                                Quisque in tempor sapien, et cursus neque. Nunc pulvinar diam ac dapibus
                                                mollis. Etiam id iaculis lorem. Donec bibendum volutpat ante, eu
                                                consequat nisi suscipit at. Etiam interdum augue dolor, id auctor felis
                                                volutpat sed. Phasellus id ex ultrices, tempus leo eget, volutpat diam.
                                                In sit amet magna faucibus, molestie nisi in, hendrerit libero. Morbi
                                                auctor velit sagittis, elementum lorem eget, imperdiet nisl.
                                            </p>
                                            <a href="#">PREVIEW</a>
                                        </div>
                                    </div>

                                    <!-- Single Portfolio Item [ END ] -->


                                    <!-- Portfolio Image -->

                                    <div class="col-lg-4 col-md-6 col-sm-4 col-xs-6 mix web-design">
                                        <div class="project">
                                            <img src="assets/img/portfolio/thumbs/image_5.jpg" alt="">
                                            <div class="ovrly">
                                            </div>
                                            <div class="buttons">
                                                <a href="#" class="fa fa-link"></a>
                                                <a href="#portfolio-5" class="fa fa-search show-popup"></a>
                                            </div>
                                        </div>
                                    </div>

                                    <!-- Popup Content -->

                                    <div class="pop-up-box" id="portfolio-5">
                                        <img alt="" src="assets/img/portfolio/image_5.jpg" class=" hidden-xs">
                                        <div class="popup-content">
                                            <h3>PROJECT NAME</h3>
                                            <p>
                                                Quisque in tempor sapien, et cursus neque. Nunc pulvinar diam ac dapibus
                                                mollis. Etiam id iaculis lorem. Donec bibendum volutpat ante, eu
                                                consequat nisi suscipit at. Etiam interdum augue dolor, id auctor felis
                                                volutpat sed. Phasellus id ex ultrices, tempus leo eget, volutpat diam.
                                                In sit amet magna faucibus, molestie nisi in, hendrerit libero. Morbi
                                                auctor velit sagittis, elementum lorem eget, imperdiet nisl.
                                            </p>
                                            <a href="#">PREVIEW</a>
                                        </div>
                                    </div>

                                    <!-- Single Portfolio Item [ END ] -->


                                    <!-- Portfolio Image -->

                                    <div class="col-lg-4 col-md-6 col-sm-4 col-xs-6 mix app-development">
                                        <div class="project">
                                            <img src="assets/img/portfolio/thumbs/image_6.jpg" alt="">
                                            <div class="ovrly">
                                            </div>
                                            <div class="buttons">
                                                <a href="#" class="fa fa-link"></a>
                                                <a href="#portfolio-6" class="fa fa-search show-popup"></a>
                                            </div>
                                        </div>
                                    </div>

                                    <!-- Popup Content -->

                                    <div class="pop-up-box" id="portfolio-6">
                                        <img alt="" src="assets/img/portfolio/image_6.jpg" class=" hidden-xs">
                                        <div class="popup-content">
                                            <h3>PROJECT NAME</h3>
                                            <p>
                                                Quisque in tempor sapien, et cursus neque. Nunc pulvinar diam ac dapibus
                                                mollis. Etiam id iaculis lorem. Donec bibendum volutpat ante, eu
                                                consequat nisi suscipit at. Etiam interdum augue dolor, id auctor felis
                                                volutpat sed. Phasellus id ex ultrices, tempus leo eget, volutpat diam.
                                                In sit amet magna faucibus, molestie nisi in, hendrerit libero. Morbi
                                                auctor velit sagittis, elementum lorem eget, imperdiet nisl.
                                            </p>
                                            <a href="#">PREVIEW</a>
                                        </div>
                                    </div>

                                    <!-- Single Portfolio Item [ END ] -->


                                    <!-- Portfolio Image -->

                                    <div class="col-lg-4 col-md-6 col-sm-4 col-xs-6 mix web-design">
                                        <div class="project">
                                            <img src="assets/img/portfolio/thumbs/image_7.jpg" alt="">
                                            <div class="ovrly">
                                            </div>
                                            <div class="buttons">
                                                <a href="#" class="fa fa-link"></a>
                                                <a href="#portfolio-7" class="fa fa-search show-popup"></a>
                                            </div>
                                        </div>
                                    </div>

                                    <!-- Popup Content -->

                                    <div class="pop-up-box" id="portfolio-7">
                                        <img alt="" src="assets/img/portfolio/image_7.jpg" class=" hidden-xs">
                                        <div class="popup-content">
                                            <h3>PROJECT NAME</h3>
                                            <p>
                                                Quisque in tempor sapien, et cursus neque. Nunc pulvinar diam ac dapibus
                                                mollis. Etiam id iaculis lorem. Donec bibendum volutpat ante, eu
                                                consequat nisi suscipit at. Etiam interdum augue dolor, id auctor felis
                                                volutpat sed. Phasellus id ex ultrices, tempus leo eget, volutpat diam.
                                                In sit amet magna faucibus, molestie nisi in, hendrerit libero. Morbi
                                                auctor velit sagittis, elementum lorem eget, imperdiet nisl.
                                            </p>
                                            <a href="#">PREVIEW</a>
                                        </div>
                                    </div>

                                    <!-- Single Portfolio Item [ END ] -->


                                    <!-- Portfolio Image -->

                                    <div class="col-lg-4 col-md-6 col-sm-4 col-xs-6 mix graphic-design">
                                        <div class="project">
                                            <img src="assets/img/portfolio/thumbs/image_8.jpg" alt="">
                                            <div class="ovrly">
                                            </div>
                                            <div class="buttons">
                                                <a href="#" class="fa fa-link"></a>
                                                <a href="#portfolio-8" class="fa fa-search show-popup"></a>
                                            </div>
                                        </div>
                                    </div>

                                    <!-- Popup Content -->

                                    <div class="pop-up-box" id="portfolio-8">
                                        <img alt="" src="assets/img/portfolio/image_8.jpg" class=" hidden-xs">
                                        <div class="popup-content">
                                            <h3>PROJECT NAME</h3>
                                            <p>
                                                Quisque in tempor sapien, et cursus neque. Nunc pulvinar diam ac dapibus
                                                mollis. Etiam id iaculis lorem. Donec bibendum volutpat ante, eu
                                                consequat nisi suscipit at. Etiam interdum augue dolor, id auctor felis
                                                volutpat sed. Phasellus id ex ultrices, tempus leo eget, volutpat diam.
                                                In sit amet magna faucibus, molestie nisi in, hendrerit libero. Morbi
                                                auctor velit sagittis, elementum lorem eget, imperdiet nisl.
                                            </p>
                                            <a href="#">PREVIEW</a>
                                        </div>
                                    </div>

                                    <!-- Single Portfolio Item [ END ] -->


                                    <!-- Portfolio Image -->

                                    <div class="col-lg-4 col-md-6 col-sm-4 col-xs-6 mix app-development">
                                        <div class="project">
                                            <img src="assets/img/portfolio/thumbs/image_9.jpg" alt="">
                                            <div class="ovrly">
                                            </div>
                                            <div class="buttons">
                                                <a href="#" class="fa fa-link"></a>
                                                <a href="#portfolio-9" class="fa fa-search show-popup"></a>
                                            </div>
                                        </div>
                                    </div>

                                    <!-- Popup Content -->

                                    <div class="pop-up-box" id="portfolio-9">
                                        <img alt="" src="assets/img/portfolio/image_9.jpg" class=" hidden-xs">
                                        <div class="popup-content">
                                            <h3>PROJECT NAME</h3>
                                            <p>
                                                Quisque in tempor sapien, et cursus neque. Nunc pulvinar diam ac dapibus
                                                mollis. Etiam id iaculis lorem. Donec bibendum volutpat ante, eu
                                                consequat nisi suscipit at. Etiam interdum augue dolor, id auctor felis
                                                volutpat sed. Phasellus id ex ultrices, tempus leo eget, volutpat diam.
                                                In sit amet magna faucibus, molestie nisi in, hendrerit libero. Morbi
                                                auctor velit sagittis, elementum lorem eget, imperdiet nisl.
                                            </p>
                                            <a href="#">PREVIEW</a>
                                        </div>
                                    </div>

                                    <!-- Single Portfolio Item [ END ] -->


                                    <!-- Portfolio Image -->

                                    <div class="col-lg-4 col-md-6 col-sm-4 col-xs-6 mix web-design">
                                        <div class="project">
                                            <img src="assets/img/portfolio/thumbs/image_10.jpg" alt="">
                                            <div class="ovrly">
                                            </div>
                                            <div class="buttons">
                                                <a href="#" class="fa fa-link"></a>
                                                <a href="#portfolio-10" class="fa fa-search show-popup"></a>
                                            </div>
                                        </div>
                                    </div>

                                    <!-- Popup Content -->

                                    <div class="pop-up-box" id="portfolio-10">
                                        <img alt="" src="assets/img/portfolio/image_10.jpg" class=" hidden-xs">
                                        <div class="popup-content">
                                            <h3>PROJECT NAME</h3>
                                            <p>
                                                Quisque in tempor sapien, et cursus neque. Nunc pulvinar diam ac dapibus
                                                mollis. Etiam id iaculis lorem. Donec bibendum volutpat ante, eu
                                                consequat nisi suscipit at. Etiam interdum augue dolor, id auctor felis
                                                volutpat sed. Phasellus id ex ultrices, tempus leo eget, volutpat diam.
                                                In sit amet magna faucibus, molestie nisi in, hendrerit libero. Morbi
                                                auctor velit sagittis, elementum lorem eget, imperdiet nisl.
                                            </p>
                                            <a href="#">PREVIEW</a>
                                        </div>
                                    </div>

                                    <!-- Single Portfolio Item [ END ] -->

                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

            <!-- Footer -->

            <div class="footer clearfix">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1 col-xs-10 col-xs-offset-1">
                        <div class="row">
                            <div class="col-md-6 col-sm-12 col-xs-12">
                                <p class="copyright">Copyright &copy; 2015
                                    <a href="#">Your Company</a>
                                </p>
                            </div>

                            <div class="col-md-6 col-sm-12 col-xs-12">
                                <p class="author">
                                    Theme by <a href="https://themewagon.com/" target="_blank">ThemeWagon</a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>