<div id="bass_pickups" class="bass-pickups-page container-fluid page">
    <div class="row">
         <div class="image-container col-md-3 col-sm-12">
            <div class="mask">
            </div>
            <div class="main-heading">
                <h1>Bass Pickups</h1>
            </div>
        </div>
        <div class="content-container col-md-9 col-sm-12">
            <div class="clearfix full-height">
                <div class="row">
                    <div class="clearfix">
                        <h2 class="small-heading">SETS</h2>
                        <div class="row">
                            <div class="col-md-10 col-md-offset-1 col-xs-10 col-xs-offset-1">
                                <div class="row">
                                    <?php include_once './sets/jbass.phtml' ?>
                                    <?php include_once './sets/pbass.phtml' ?>
                                    <?php include_once './sets/p51.phtml' ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <?php include 'footer.phtml'; ?>
        </div>
    </div>
</div>