<div id="custom" class="service-page container-fluid page">
    <div class="row">
        <div class="image-container col-md-3 col-sm-12">
            <div class="mask">
            </div>
            <div class="main-heading">
                <h1>Service</h1>
            </div>
        </div>
        <div class="content-container col-md-9 col-sm-12">
            <div class="clearfix">
                <h2 class="small-heading">WHAT WE DO BEST</h2>
                <div class="row">
                    <div class="col-md-10 col-md-offset-1 col-sm-12">
                        <div class="row">
                            <div class="col-md-4 col-sm-12">
                                <div class="faq-desc-item">
                                    <div class="flip-container text-center" ontouchstart="this.classList.toggle('hover');">
                                        <div class="flipper">
                                            <div class="front">
                                                <i class="fa fa-mobile"></i>
                                                <h5>Applications</h5>
                                            </div>
                                            <div class="back">
                                                <h5>Applications</h5>
                                                <p>Mozilla Web Developer, MooTools &amp; jQuery Consultant, MooTools Core Developer, Javascript Fanatic, CSS Tinkerer, PHP Hacker, and web lover.</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-4 col-sm-12">
                                <div class="faq-desc-item">
                                    <div class="flip-container text-center" ontouchstart="this.classList.toggle('hover');">
                                        <div class="flipper">
                                            <div class="front">
                                                <i class="fa fa-lightbulb-o"></i>
                                                <h5>Productions</h5>
                                            </div>
                                            <div class="back">
                                                <!-- <i class="fa fa-lightbulb-o fa-fw"></i> -->
                                                <h5>Productions</h5>
                                                <p>Mozilla Web Developer, MooTools &amp; jQuery Consultant, MooTools Core Developer, Javascript Fanatic, CSS Tinkerer, PHP Hacker, and web lover.</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4 col-sm-12">
                                <div class="faq-desc-item">
                                    <div class="flip-container text-center" ontouchstart="this.classList.toggle('hover');">
                                        <div class="flipper">
                                            <div class="front">
                                                <i class="fa fa-paint-brush"></i>
                                                <h5>Web Designing</h5>
                                            </div>
                                            <div class="back">
                                                <!-- <i class="fa fa-paint-brush fa-fw"></i> -->
                                                <h5>Web Designing</h5>
                                                <p>Mozilla Web Developer, MooTools &amp; jQuery Consultant, MooTools Core Developer, Javascript Fanatic, CSS Tinkerer, PHP Hacker, and web lover.</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="clearfix">
                <h2 class="small-heading">CHOSSE YOUR PLAN</h2>
                <div class="row">
                    <div class="col-md-10 col-md-offset-1 col-xs-10 col-xs-offset-1">
                        <div class="row">
                            <div class="col-md-6 col-sm-6 col-xs-12 price-catagory">
                                <div class="price-box">
                                    <p class="pricing-catagory-name">Basic</p>
                                    <p><span class="price">$19</span>/Month</p>
                                    <ul>
                                        <li>15 Projects</li>
                                        <li>30 GB Storage</li>
                                        <li class="unavailabe">Unlimited Data Transfer</li>
                                        <li class="unavailabe">50 GB Bandwith</li>
                                        <li class="unavailabe">Enhanced Security</li>
                                    </ul>
                                    <a href="#" class="btn">learn more</a>
                                </div>
                            </div>
                            <div class="col-md-6 col-sm-6 col-xs-12 price-catagory">
                                <div class="price-box">
                                    <p class="pricing-catagory-name">Business</p>
                                    <p><span class="price">$29</span>/Month</p>
                                    <ul>
                                        <li>15 Projects</li>
                                        <li>30 GB Storage</li>
                                        <li>Unlimited Data Transfer</li>
                                        <li class="unavailabe">50 GB Bandwith</li>
                                        <li class="unavailabe">Enhanced Security</li>
                                    </ul>
                                    <a href="#" class="btn">learn more</a>
                                </div>
                            </div>
                            <div class="col-md-6 col-sm-6 col-xs-12 price-catagory">
                                <div class="price-box">
                                    <p class="pricing-catagory-name">Premium</p>
                                    <p><span class="price">$39</span>/Month</p>
                                    <ul>
                                        <li>15 Projects</li>
                                        <li>30 GB Storage</li>
                                        <li>Unlimited Data Transfer</li>
                                        <li>50 GB Bandwith</li>
                                        <li class="unavailabe">Enhanced Security</li>
                                    </ul>
                                    <a href="#" class="btn">learn more</a>
                                </div>
                            </div>
                            <div class="col-md-6 col-sm-6 col-xs-12 price-catagory">
                                <div class="price-box">
                                    <p class="pricing-catagory-name">Ultimate</p>
                                    <p><span class="price">$49</span>/Month</p>
                                    <ul>
                                        <li>15 Projects</li>
                                        <li>30 GB Storage</li>
                                        <li>Unlimited Data Transfer</li>
                                        <li>50 GB Bandwith</li>
                                        <li>Enhanced Security</li>
                                    </ul>
                                    <a href="#" class="btn">learn more</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
             <div class="clearfix full-height">
                <h2 class="small-heading">OUR VALUABLE CLIENTS</h2>
                <div class="row">
                    <div class="col-md-10 col-md-offset-1 col-xs-10 col-xs-offset-1">
                        <div id="sponsor-list" class="owl-carousel owl-theme">
                            <div class="item">
                                <img src="assets/img/sponsor1.png" alt="sponsor1" class="center-block" style="width: 165px; height: 127px;">
                            </div>
                            <div class="item">
                                <img src="assets/img/sponsor2.png" alt="sponsor2" class="center-block" style="width: 165px; height: 127px;">
                            </div>
                            <div class="item">
                                <img src="assets/img/sponsor3.png" alt="sponsor3" class="center-block" style="width: 165px; height: 127px;">
                            </div>
                            <div class="item">
                                <img src="assets/img/sponsor4.png" alt="sponsor4" class="center-block" style="width: 165px; height: 127px;" >
                            </div>
                            <div class="item">
                                <img src="assets/img/sponsor5.png" alt="sponsor5" class="center-block" style="width: 165px; height: 127px;">
                            </div>
                            <div class="item">
                                <img src="assets/img/sponsor6.png" alt="sponsor6" class="center-block" style="width: 165px; height: 127px;">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
             <?php include 'footer.phtml'; ?>
        </div>
    </div>
</div>