<div id="custom" class="service-page container-fluid page">
    <div class="row">
        <!--( a ) Contact Page Fixed Image Portion -->

        <div class="image-container col-md-3 col-sm-12">
            <div class="mask">
            </div>
            <div class="main-heading">
                <h1>Custom Guitars & Basses</h1>
            </div>
        </div>

        <!--( b ) Contact Page Content -->

        <div class="content-container col-md-9 col-sm-12">

            <!--( A ) Contact Form -->

            <div class="clearfix full-height">
                <h2 class="small-heading">COMING SOON</h2>

            </div>

            <!-- ( D ) Footer -->

            <?php require_once 'footer.phtml'; ?>
        </div>
    </div>
</div>