<div class="footer clearfix">
    <div class="row">
        <div class="col-md-10 col-md-offset-1 col-xs-10 col-xs-offset-1">
            <div class="row">
                <div class="col-md-6 col-sm-12 col-xs-12">
                    <p class="copyright">Copyright &copy; 2014 - <?=date('Y');?>
                        <a href="#" style="color: white">SB Custom</a>
                    </p>
                </div>
                <div class="col-md-6 col-sm-12 col-xs-12">
                    <p class="author">
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>