<div id="gallery" class="portfolio-page container-fluid page">
    <div class="row">
        <div class="image-container col-md-3 col-sm-12">
            <div class="mask">
            </div>
            <div class="main-heading">
                <h1>Comming Soon</h1>
            </div>
        </div>
        <div class="content-container col-md-9 col-sm-12">
            <div class="portfolio clearfix full-height">
                <h2 class="small-heading-silver">Gallery</h2>
                <div class="row">
                    <div class="col-md-10 col-md-offset-1 col-xs-10 col-xs-offset-1">
                        <div class="project-container">
                            <div class="row">
                                <!-- Portfolio Control Buttons [ END ] -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <?php include "footer.phtml" ?>
        </div>
    </div>
</div>
