<div id="guitar_pickups" class="guitar-pickups-page container-fluid page">
    <div class="row">
        <!--( a ) Portfolio Page Fixed Image Portion -->

        <div class="image-container col-md-3 col-sm-12">
            <div class="mask">
            </div>
            <div class="main-heading">
                <h1>Guitar Pickups</h1>
            </div>
        </div>

        <!--( b ) Portfolio Page Content -->

        <div class="content-container col-md-9 col-sm-12">

            <!--( A ) Portfolio -->

            <div class="clearfix">
                <h2 class="small-heading">GUITAR PICKUPS</h2>
                <div class="row">
                    <div class="col-md-10 col-md-offset-1 col-sm-12">
                        <div class="row">

                            <div class="col-md-3 col-sm-12">
                                <div class="faq-desc-item">
                                    <div class="flip-container text-center">
                                        <div class="flipper" >
                                            <div class="front">
                                                <h5><a href="#stratocaster-set">Stratocaster</a><sup>&trade;</sup></h5>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-3 col-sm-12">
                                <div class="faq-desc-item">
                                    <div class="flip-container text-center">
                                        <div class="flipper">
                                            <div class="front">
                                                <h5><a href="#telecaster-set">Telecaster</a><sup>&trade;</sup></h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-3 col-sm-12">
                                <div class="faq-desc-item">
                                    <div class="flip-container text-center">
                                        <div class="flipper">
                                            <div class="front">

                                                <h5><a href="#humbucker-set">Humbuckers</a></h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-3 col-sm-12">
                                <div class="faq-desc-item">
                                    <div class="flip-container text-center">
                                        <div class="flipper">
                                            <div class="front">

                                                <h5><a href="#p90-set">P90</a><sup>&reg;</sup></h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>





            <?php include_once ('./sets/strat.phtml')?>

            <?php include_once ('./sets/tele.phtml')?>

            <?php include_once ('./sets/humbuckers.phtml')?>

            <?php include_once ('./sets/p90.phtml')?>

            

            
            <!-- end: pricing section -->



            <!-- end: valuable clients -->




            <!-- Footer -->

            <div class="footer clearfix">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1 col-xs-10 col-xs-offset-1">
                        <div class="row">
                            <div class="col-md-6 col-sm-12 col-xs-12">
                                <p class="copyright">Copyright &copy; <?=date('Y');?>
                                    <a href="#" style="color: white">SB Custom</a>
                                </p>
                            </div>

                            <div class="col-md-6 col-sm-12 col-xs-12">
                                <p class="author">

                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
</div>