<div id="guitar_pickups" class="guitar-pickups-page container-fluid page">
    <div class="row">
        <div class="image-container col-md-3 col-sm-12">
            <div class="mask">
            </div>
            <div class="main-heading">
                <h1>Guitar Pickups</h1>
            </div>
        </div>
        <div class="content-container col-md-9 col-sm-12">
            <div class="clearfix">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1 col-sm-12">
                        <div class="row">
                            <div class="col-md-3 col-xs-3" style="display:block;text-align:center;">
                                <a href="#stratocaster-set" class="btn-guitars"><i class="icon-sb-stratocaster-icon"></i> Stratocaster</a>
                            </div>
                            <div class="col-md-3 col-xs-3" style="display:block;text-align:center;">
                                <a href="#telecaster-set" class="btn-guitars"><i class="icon-sb-telecaster-icon"></i> Telecaster</a>
                            </div>
                            <div class="col-md-3 col-xs-3" style="display:block;text-align:center;">
                                <a href="#humbucker-set" class="btn-guitars"><i class="icon-sb-les-paul-icon"></i> Humbuckers</a>
                            </div>
                            <div class="col-md-3 col-xs-3" style="display:block;text-align:center;">
                                <a href="#p90-set" class="btn-guitars"><i class="icon-sb-335-icon"></i> P90</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <?php include_once ('./sets/strat.phtml')?>
            <?php include_once ('./sets/tele.phtml')?>
            <?php include_once ('./sets/humbuckers.phtml')?>
            <?php include_once ('./sets/p90.phtml')?>
            <?php include 'footer.phtml'; ?>
        </div>
    </div>
</div>