<div class="home-page">

    <!-- Introduction -->

    <div class="introduction">
        <!-- <div class="mask">
        </div> -->
        <div class="intro-content">
            <!-- <h1>HELLO<br>
            I'M <span>JOHN</span> DOE</h1> -->

            <span>SB Custom</span><span class="number"></span>
            <p class="slogan-text text-capitalize">
                Boutique Handwound Pickups <i class="fa fa-adjust" style="color: #8a6e4b"></i> Custom Guitars and Bass
                <br>
                <div style="font-size: 90%;text-align: center">"You dream... we build"</div>
            </p>


            <div class="social-media hidden-xs">
                <a href="https://wwww.facebook.com/sbcustompt" target="_blank" class="fa fa-facebook" data-toggle="tooltip" title="Facebook"></a>
                <a href="https://www.instagram.com/sb_custom_pt/" class="fa fa-instagram" data-toggle="tooltip" title="Instagram"></a>
                <a href="mailto:info@sbcustom.pt" class="fa fa-envelope" data-toggle="tooltip" title="Email"></a>
            </div>
        </div>

        <!-- Social Media Icons [ END ] -->
    </div>

    <!-- Navigation Menu -->

    <div class="menu">
        <div data-url_target="guitar_pickups" class="profile-btn menu_button">
            <img alt="" src="assets/images/guitar-pickups-intro.png" style="width:100%; height:100%;">
            <div class="mask">
            </div>
            <div class="heading">
                <i class="ion-ios-people-outline hidden-xs"></i>
                <h2>Guitar Pickups</h2>
            </div>
        </div>

        <!-- Single Navigation Menu Button -->

        <div data-url_target="bass_pickups" class="portfolio-btn menu_button">
            <img alt="" src="assets/images/bass-pickups-intro.png">
            <div class="mask">
            </div>
            <div class="heading">
                <i class="ion-ios-briefcase-outline hidden-xs"></i>
                <h2>Bass Pickups</h2>
            </div>
        </div>

        <!-- Single Navigation Menu Button [ END ]  -->

        <div data-url_target="custom" class="service-btn menu_button">
            <img alt="" src="assets/images/custom-guitars.png">
            <div class="mask">
            </div>
            <div class="heading">
                <i class="ion-ios-lightbulb-outline hidden-xs"></i>
                <h2>Custom Guitars & Bass</h2>
            </div>
        </div>

        <!-- Single Navigation Menu Button [ END ]  -->

        <div data-url_target="service" class="contact-btn menu_button">
            <img alt="" src="assets/images/services.png">
            <div class="mask">
            </div>
            <div class="heading">
                <i class="ion-ios-chatboxes-outline hidden-xs"></i>
                <h2>Services</h2>
            </div>
        </div>

        <!-- Single Navigation Menu Button [ END ]  -->

    </div>
</div>