<div id="premium" class="contact-page container-fluid page">
    <div class="row">
        <!--( a ) Contact Page Fixed Image Portion -->

        <div class="image-container col-md-3 col-sm-12">
            <div class="mask">
            </div>
            <div class="main-heading">
                <h1>premium custom</h1>
            </div>
        </div>

        <!--( b ) Contact Page Content -->

        <div class="content-container col-md-9 col-sm-12">

            <!--( A ) Contact Form -->

            <div class="clearfix full-height">
                <h2 class="small-heading">Premium Custom <br> <small>Our finnest</small></h2>

                <div class="col-md-4 col-sm-6 col-xs-12">
                    <div class="faq-desc-item-premium">
                        <div class="flip-container-premium text-center" ontouchstart="this.classList.toggle('hover');">
                            <div class="flipper-premium">
                                <div class="front-premium gold-border">
                                    <img src="/assets/images/premium/croft.png" alt="">
                                    <h5>“Croft” P90 Neck Pickup</h5>
                                </div>
                                <div class="back-premium">
                                    <h5>For: Ergon Guitar Porto</h5>
                                    <p>This P90's was built for the neck pickup of Ergon Guitar by Adriano Sérgio - Porto Guitar</p>
                                    <p>Featuring Alnico V, with 42 AWG Plain Enamel, this pickup also have a Coil Tap for extra boost.</p>
                                    <img src="/assets/images/premium/porto_guitar90.png" alt="">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-4 col-sm-6 col-xs-12">
                    <div class="faq-desc-item-premium">
                        <div class="flip-container-premium text-center" ontouchstart="this.classList.toggle('hover');">
                            <div class="flipper-premium">
                                <div class="front-premium gold-border">
                                    <img src="/assets/images/premium/dows.png" alt="">
                                    <h5>“Dow’s” Bridge Humbucker</h5>
                                </div>
                                <div class="back-premium">
                                    <h5>For: Ergon Guitar Porto</h5>
                                    <p>This Humbucker was built for the Bridge Pickup of Ergon Guitar by Adriano Sérgio - Porto Guitar</p>
                                    <p>Featuring Alnico II, with 42 AWG Plain Enamel, this pickup also have a Coil Tap for extra boost.</p>
                                    <img src="/assets/images/premium/porto_guitar2.png" alt="">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-4 col-sm-6 col-xs-12">
                    <div class="faq-desc-item-premium">
                        <div class="flip-container-premium text-center" ontouchstart="this.classList.toggle('hover');">
                            <div class="flipper-premium">
                                <div class="front-premium gold-border">
                                    <img src="/assets/images/premium/cintra.png" alt="">
                                    <h5>“Seteais” Bass Set</h5>
                                </div>
                                <div class="back-premium">
                                    <h5>For: Ergon Guitars - Bass Cintra</h5>
                                    <p>This set was built for the Ergon Guitars by Adriano Sérgio - Cintra Bass</p>
                                    <p>This set was made using a "secret sauce", for a very special bass. This is the first bass, ever made by Ergon Guitar</p>
                                    <img src="/assets/images/premium/cintra_bass90.png" alt="">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-4 col-sm-6 col-xs-12">
                    <div class="faq-desc-item-premium">
                        <div class="flip-container-premium text-center" ontouchstart="this.classList.toggle('hover');">
                            <div class="flipper-premium">
                                <div class="front-premium gold-border">
                                    <img src="/assets/images/premium/simon.png" alt="">
                                    <h5>“Simon” Bass Set</h5>
                                </div>
                                <div class="back-premium">
                                    <h5>For: Custom Build Bass</h5>
                                    <p>This set came to us, for repair from an initial malfunction and low output.</p>
                                    <p></p>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

            <!-- ( D ) Footer -->

            <div class="footer clearfix">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1 col-xs-10 col-xs-offset-1">
                        <div class="row">
                            <div class="col-md-6 col-sm-12 col-xs-12">
                                <p class="copyright">Copyright &copy; <?=date('Y');?>
                                    <a href="#" style="color: white">SB Custom</a>
                                </p>
                            </div>

                            <div class="col-md-6 col-sm-12 col-xs-12">
                                <p class="author">

                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>