<div class="clearfix">
    <h2 class="small-heading" id="humbucker-set">HUMBUCKERS SETS</h2>
    <div class="row">
        <div class="col-md-10 col-md-offset-1 col-xs-10 col-xs-offset-1">
            <div class="row">
                <div class="col-md-6 price-category-gold">
                    <div class="price-box">
                        <p class="set-name">Vintage Series</p>
                        <p><span class="price"></span></p>
                        <p class="description">Inspired by the late 50's sound, this pickups uses Alnico 2 magnets, for
                            a smooth, yet crunchy humbucker sound with slightly enhanced highs. Perfect for Classic Rock
                            and Blues Rock tones</p>
                        <div class="col-md-6">
                            <ul style="text-align: left;">
                                <li><i class="fa fa-check-square-o specs-gold"></i> Brass baseplate</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Alnico 2</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> 42 AWG Plain Enamel Wire</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Fabric-taped</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Double Black, Zebra, Nickel or Gold
                                    Cover
                                </li>
                            </ul>
                        </div>
                        <div class="col-md-6" style="padding-bottom: 20px">
                            <ul style="text-align: left">
                                <li><i class="fa fa-check-square-o specs-gold"></i> Neck Pickup Resistance: ~ 6,5 K</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Bridge Pickup Resistance: ~ 7,5 K
                                </li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Wax-potted</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Overwound on request</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Output wire: 2 or 5 conductors</li>
                            </ul>
                        </div>
                        <p class="description text-90"><?=SBCustom\CommonStrings::text('pickups_description_box')?></p>
                        <div class="addthis_inline_share_toolbox top-20"></div>
                        <a href="mailto:info@sbcustom.pt?subject=Humbucker Vintage Series Info" class="btn"><i
                                class="fa fa-envelope"></i> info</a>
                    </div>
                </div>
                <div class="col-md-6 price-category-gold">
                    <div class="price-box">
                        <p class="set-name">Modern Series</p>
                        <p><span class="price"></span></p>
                        <p class="description">Based on the Vintage Series, this set uses Alnico 5 for a more aggressive
                            sound, retaining the smooth, crunchy sound. They are a perfect replacement, if you need a
                            more full, powerfull sound. Ideal for Rock.</p>
                        <div class="col-md-6">
                            <ul style="text-align: left;">
                                <li><i class="fa fa-check-square-o specs-gold"></i> Brass baseplate</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Alnico 5</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> 42 AWG Natural Enamel Wire</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Fabric-taped</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Double Black, Zebra, Nickel or Gold
                                    Cover
                                </li>
                            </ul>
                        </div>
                        <div class="col-md-6" style="padding-bottom: 20px">
                            <ul style="text-align: left">
                                <li><i class="fa fa-check-square-o specs-gold"></i> Neck Pickup Resistance: ~ 7 K</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Bridge Pickup Resistance: ~ 8 K</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Wax-potted</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Overwound on request</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Output wire: 2 or 5 conductors</li>
                            </ul>
                        </div>
                        <p class="description text-90"><?=SBCustom\CommonStrings::text('pickups_description_box')?></p>
                        <div class="addthis_inline_share_toolbox top-20"></div>
                        <a href="mailto:info@sbcustom.pt?subject=Humbucker Modern Series Info" class="btn"><i
                                class="fa fa-envelope"></i> info</a>
                    </div>
                </div>
                <div class="col-md-6 price-category-gold">
                    <div class="price-box">
                        <p class="set-name">Modern PAF</p>
                        <p><span class="price"></span></p>
                        <p class="description">This set uses the specifications of an old PAF Humbucker, with a
                            different Alnico and wire type, so you can retain the classic sound, but with more power and
                            crunch. This set is a must for the modern Blues/Rock guitarist.</p>
                        <div class="col-md-6">
                            <ul style="text-align: left;">
                                <li><i class="fa fa-check-square-o specs-gold"></i> Brass baseplate</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Alnico 5</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> 42 AWG Natural Enamel Wire</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Fabric-taped</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Double Black, Zebra, Nickel or Gold
                                    Cover
                                </li>
                            </ul>
                        </div>
                        <div class="col-md-6" style="padding-bottom: 20px">
                            <ul style="text-align: left">
                                <li><i class="fa fa-check-square-o specs-gold"></i> Neck Pickup Resistance: ~ 7 K</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Bridge Pickup Resistance: ~ 8 K</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Wax-potted</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Overwound on request</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Output wire: 2 or 5 conductors</li>
                            </ul>
                        </div>
                        <p class="description text-90"><?=SBCustom\CommonStrings::text('pickups_description_box')?></p>
                        <div class="addthis_inline_share_toolbox top-20"></div>
                        <a href="mailto:info@sbcustom.pt?subject=Humbucker Modern PAF Info" class="btn"><i
                                class="fa fa-envelope"></i> info</a>
                    </div>
                </div>
                <div class="col-md-6 price-category-gold">
                    <div class="price-box">
                        <p class="set-name">True PAF Gold Line</p>
                        <p><span class="price"></span></p>
                        <p class="description">This is the Top of The Line. Uses the same exact specifications of an
                            old PAF, made by Seth Lover. With the exact Alnico and wire type, used in the days. With
                            "unmatched” bobbin windings, when overdriven they achieve a magical overdrive, that PAF are
                            famous for.</p>
                        <div class="col-md-6">
                            <ul style="text-align: left;">
                                <li><i class="fa fa-check-square-o specs-gold"></i> Brass baseplate</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Alnico 2</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> 42 AWG Plain Enamel Wire</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Fabric-taped</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Double Black, Zebra, Nickel or Gold
                                    Cover
                                </li>
                            </ul>
                        </div>
                        <div class="col-md-6" style="padding-bottom: 20px">
                            <ul style="text-align:left;">
                                <li><i class="fa fa-check-square-o specs-gold"></i> Neck Pickup Resistance: ~ 6,5 K</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Bridge Pickup Resistance: ~ 7,5 K
                                </li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Wax-potted</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Overwound on request</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Output wire: 2 conductors</li>
                            </ul>
                        </div>
                        <p class="description text-90 top-p-20"><?=SBCustom\CommonStrings::text('pickups_description_box')?></p>
                        <div class="addthis_inline_share_toolbox top-20"></div>
                        <a href="mailto:info@sbcustom.pt?subject=Humbucker True PAF Gold Line Info" class="btn"><i
                                class="fa fa-envelope"></i> info</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>