<div class="col-md-6 price-category-gold">
    <div class="price-box">
        <p class="set-name" id="j-bass">Vintage J-Bass<sup>&trade;</sup> Style</p>
        <p><span class="price"></span></p>
        <p class="description">This pickups take the classic Jazz Bass pickup style and realy deliver the goods. Smooth and punchy tone, with even response throughout the strings. RW/RP for hum free operation when combined with the neck pickup. We offer the choice of Natural Enamel or Plain Enamel wire </p>
        <div class="col-md-12">
            <p class="gold">Set</p>
            <ul style="text-align: left;">
                <li><i class="fa fa-check-square-o specs-gold"></i> Vintage correct vulcanized fiber work</li>
                <li><i class="fa fa-check-square-o specs-gold"></i> 0.187" Alnico 5 flush mounted sand cast polepiece magnets.</li>
                <li><i class="fa fa-check-square-o specs-gold"></i> E: 0.780"  A: 0.780"  D: 0.780" G: 0.780"</li>
                <li><i class="fa fa-check-square-o specs-gold"></i> Bridge pickup is RW/RP</li>
                <li><i class="fa fa-check-square-o specs-gold"></i> Vintage style pushback wire</li>
                <li><i class="fa fa-check-square-o specs-gold"></i> DC Resistance: ~ 8,5K</li>
                <li><i class="fa fa-check-square-o specs-gold"></i> 42 AWG Plain Enamel Wire / Enamel Wire</li>
                <li><i class="fa fa-check-square-o specs-gold"></i> Wax-potted</li>
                <li><i class="fa fa-check-square-o specs-gold"></i> Overwound on request</li>
            </ul>
        </div>

        <p>&nbsp;</p>

        <p class="description text-90">Like all SB Custom pickups these are shipped in a premium product box, and come with all mounting hardware and a wiring diagram.</p>
        <a href="mailto:info@sbcustom.pt?subject=Vintage J-Bass" class="btn"><i class="fa fa-envelope"></i> info</a>
    </div>
</div>