<div class="col-md-6 price-category-gold">
    <div class="price-box">
        <p class="set-name" id="p-bass-51">Vintage '51 P-Bass<sup>&trade;</sup> Style
            <small><em>aka Tele<sup>&trade;</sup> Bass</em></small>
        </p>
        <p><span class="price"></span></p>
        <p class="description">Loud, clear, and punchy, this great single coil is the perfect replacement for the "<em>most
                cool bass ever!</em>".
        </p>
        <div class="col-md-12">
            <p class="gold">Set</p>
            <ul style="text-align: left;">
                <li><i class="fa fa-check-square-o specs-gold"></i> Vintage correct vulcanized fiber work</li>
                <li><i class="fa fa-check-square-o specs-gold"></i> 0.195" Alnico 5 vintage flush mounted sand cast
                    polepiece magnets with vintage beveled top
                </li>
                <li><i class="fa fa-check-square-o specs-gold"></i> E: 0.630" A: 0.630" D: 0.630 G: 0.630"</li>
                <li><i class="fa fa-check-square-o specs-gold"></i> Vintage style pushback wire</li>
                <li><i class="fa fa-check-square-o specs-gold"></i> 42 AWG Heavy Formvar Wire</li>
                <li><i class="fa fa-check-square-o specs-gold"></i> DC Resistance: ~ 9,5K</li>
                <li><i class="fa fa-check-square-o specs-gold"></i> Wax-potted</li>
                <li><i class="fa fa-check-square-o specs-gold"></i> Overwound on request</li>
            </ul>
        </div>
        <p>&nbsp;</p>
        <p class="description text-90"><?=SBCustom\CommonStrings::text('pickups_description_box')?></p>
        <div class="addthis_inline_share_toolbox top-20"></div>
        <a href="mailto:info@sbcustom.pt?subject=Vintage 51 P-Bass Info" class="btn"><i class="fa fa-envelope"></i>
            info</a>
    </div>
</div>