<div class="clearfix">
    <h2 class="small-heading" id="p90-set">P90 SETS</h2>
    <div class="row">
        <div class="col-md-10 col-md-offset-1 col-xs-10 col-xs-offset-1">
            <div class="row">
                <div class="col-md-6 price-category-gold">
                    <div class="price-box">
                        <p class="set-name">P90</p>
                        <p><span class="price"></span></p>
                        <p class="description"></p>
                        <div class="col-md-6">
                            <ul style="text-align: left;">
                                <li><i class="fa fa-check-square-o specs-gold"></i> Vintage correct vulcanized fiber work</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> 0.195" Alnico 3 vintage bevel top polepiece magnets</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> E: 0.671"  A: 0.671"  D: 0.710"</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> G: 0.671"  B: 0.630"  E: 0.650"</li>

                            </ul>
                        </div>
                        <div class="col-md-6" style="padding-bottom: 20px">
                            <ul style="text-align: left">
                                <li><i class="fa fa-check-square-o specs-gold"></i> Middle Pickup is RW/RP</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Vintage style push-back wire</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> 42 AWG Heavy Formvar Wire</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> DC Resistance: ~ 5.8 K</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Wax-potted</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Overwound on request</li>
                            </ul>
                        </div>
                        <p><span class="price"><i class="fa fa-info-circle"></i></span></p>
                        <p class="description text-90">Like all SB Custom pickups these are shipped in product box with custom foam inserts, and come with all mounting hardware and a wiring diagram.</p>
                    </div>
                </div>

                <div class="col-md-6 price-category-gold">
                    <div class="price-box">
                        <p class="set-name">P90</p>
                        <p><span class="price"></span></p>
                        <p class="description"></p>
                        <div class="col-md-6">
                            <ul style="text-align: left;">
                                <li><i class="fa fa-check-square-o specs-gold"></i> Vintage correct vulcanized fiber work</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> 0.195" Alnico 3 vintage bevel top polepiece magnets</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> E: 0.671"  A: 0.671"  D: 0.710"</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> G: 0.671"  B: 0.630"  E: 0.650"</li>

                            </ul>
                        </div>
                        <div class="col-md-6" style="padding-bottom: 20px">
                            <ul style="text-align: left">
                                <li><i class="fa fa-check-square-o specs-gold"></i> Middle Pickup is RW/RP</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Vintage style push-back wire</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> 42 AWG Heavy Formvar Wire</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> DC Resistance: ~ 5.8 K</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Wax-potted</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Overwound on request</li>
                            </ul>
                        </div>
                        <p><span class="price"><i class="fa fa-info-circle"></i></span></p>
                        <p class="description text-90">Like all SB Custom pickups these are shipped in product box with custom foam inserts, and come with all mounting hardware and a wiring diagram.</p>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>