<div class="clearfix">
    <h2 class="small-heading" id="p90-set">P90 SETS</h2>
    <div class="row">
        <div class="col-md-10 col-md-offset-1 col-xs-10 col-xs-offset-1">
            <div class="row">
                <div class="col-md-6 price-category-gold">
                    <div class="price-box">
                        <p class="set-name">Vintage Series</p>
                        <p><span class="price"></span></p>
                        <p class="description">What not to like in a P90. It's just a full, rich fat sound. In this serie we use Alnico 3 for a true Vintage Sound. With a thick Single-Coil tone, this is a must for any serious guitarist. </p>
                        <div class="col-md-12">
                            <p class="gold">Dog Ear Set / Soapbar Set</p>
                       </div>
                        <div class="col-md-6">
                            <ul style="text-align: left;">
                                <li><i class="fa fa-check-square-o specs-gold"></i> P-90 dog ear style fiber bobbin with hard maple shim pre-glued and tapped to accept a standard 5-40 pole piece</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> 50mm pole spacing</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Alnico 3</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Six 1018 and six 1022 steel nickel plated fillister head pole pieces </li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Two nickel plated mounting screws</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Two nickel plated baseplate screws</li>
                            </ul>
                        </div>
                        <div class="col-md-6">
                            <p class="gold"></p>
                            <ul style="text-align: left;">
                                <li><i class="fa fa-check-square-o specs-gold"></i> Steel pole shoe</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Nickel silver baseplate</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> 28 AWG 2 conductor shielded wire with a bare drain</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> 42 AWG Natural Enamel Wire</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Bridge pickup is RW/RP</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> DC Resistance: ~ 7,5K</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Wax-potted</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Overwound on request</li>
                            </ul>
                        </div>
                        <p class="description text-90"><?=SBCustom\CommonStrings::text('pickups_description_box')?></p>
                        <div class="addthis_inline_share_toolbox top-20"></div>
                        <a href="mailto:info@sbcustom.pt?subject=P90" class="btn"><i
                                class="fa fa-envelope"></i> info</a>
                    </div>
                </div>
                <div class="col-md-6 price-category-gold">
                    <div class="price-box">
                        <p class="set-name">Modern Series</p>
                        <p><span class="price"></span></p>
                        <p class="description">Much like the Vintage Series, this set offers Alnico 5 and a bit more output, for a more cutting edge, and growl.</p>
                        <p>&nbsp;</p>
                        <div class="col-md-12">
                            <p class="gold">Dog Ear Set / Soapbar Set</p>
                        </div>
                        <div class="col-md-6">
                            <ul style="text-align: left;">
                                <li><i class="fa fa-check-square-o specs-gold"></i> P-90 dog ear style fiber bobbin with hard maple shim pre-glued and tapped to accept a standard 5-40 pole piece</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> 50mm pole spacing</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Alnico 5</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Six 1018 and six 1022 steel nickel plated fillister head pole pieces </li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Two nickel plated mounting screws</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Two nickel plated baseplate screws</li>
                            </ul>
                        </div>
                        <div class="col-md-6">
                            <p class="gold"></p>
                            <ul style="text-align: left;">
                                <li><i class="fa fa-check-square-o specs-gold"></i> Steel pole shoe</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Nickel silver baseplate</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> 28 AWG 2 conductor shielded wire with a bare drain</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> 42 AWG Natural Enamel Wire</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Bridge pickup is RW/RP</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> DC Resistance: ~ 9,5K</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Wax-potted</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Overwound on request</li>
                            </ul>
                        </div>
                        <p class="description text-90 top-20"><?=SBCustom\CommonStrings::text('pickups_description_box')?></p>
                        <div class="addthis_inline_share_toolbox top-20"></div>
                        <a href="mailto:info@sbcustom.pt?subject=P90" class="btn"><i
                                class="fa fa-envelope"></i> info</a>
                    </div>
                </div>
                <div class="col-md-6 price-category-gold">
                    <div class="price-box">
                        <p class="set-name">Jazzmaster</p>
                        <p><span class="price"></span></p>
                        <p class="description">The unique sound of the Jazzmaster, had appeal to many guitarists, all over the years. From the early 60's Surf Sound to the 90's Grunge, the dark, warm tone of this pickup, is legendary. Our replacement set will give you a true Vintage tone for your guitar</p>
                        <div class="col-md-12">
                            <ul style="text-align: left;">
                                <li><i class="fa fa-check-square-o specs-gold"></i> Vintage correct vulcanized fiber work</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> 0.187" Alnico 2 vintage flush mounted sand cast polepiece magnets with vintage bevel top
                                    E: 0.471  A: 0.471  D: 0.471  G: 0.471  B: 0.471  e: 0.471</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Nickel plated pickup mounting screws included</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Vintage style push-back wires </li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> 42 AWG Heavy Formvar Wire </li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Bridge pickup is RW/RP</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> DC Resistance: ~ 7,5K - 7,8K</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Wax-potted</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Overwound on request</li>
                            </ul>
                        </div>
                        <p class="description text-90 top-20"><?=SBCustom\CommonStrings::text('pickups_description_box')?></p>
                        <div class="addthis_inline_share_toolbox top-20"></div>
                        <a href="mailto:info@sbcustom.pt?subject=Jazzmaster" class="btn"><i
                                class="fa fa-envelope"></i> info</a>
                    </div>
                </div></div>
        </div>
    </div>
</div>