<div class="col-md-6 price-category-gold">
    <div class="price-box">
        <p class="set-name" id="p-bass">Vintage P-Bass<sup>&trade;</sup> Style</p>
        <p><span class="price"></span></p>
        <p class="description">This set add a smooth round to your bass. They have a tone and character, and wide
            frequency response, this pickup allow players to shape their sound.
            Every note is balanced and smooth across all strings. A great replacement.
        </p>
        <div class="col-md-12">
            <p class="gold">Set</p>
            <ul style="text-align: left;">
                <li><i class="fa fa-check-square-o specs-gold"></i> Vintage correct vulcanized fiber work</li>
                <li><i class="fa fa-check-square-o specs-gold"></i> 0.195" Alnico 5 Flush mounted Alnico sand cast
                    polepiece magnets
                </li>
                <li><i class="fa fa-check-square-o specs-gold"></i> E: 0.531" A: 0.531" D: 0.531 G: 0.531"</li>
                <li><i class="fa fa-check-square-o specs-gold"></i> One pickup is RW/RP"</li>
                <li><i class="fa fa-check-square-o specs-gold"></i> Vintage style pushback wire</li>
                <li><i class="fa fa-check-square-o specs-gold"></i> 42 AWG Heavy Formvar Wire / Enamel Wire</li>
                <li><i class="fa fa-check-square-o specs-gold"></i> DC Resistance: ~ 11K</li>
                <li><i class="fa fa-check-square-o specs-gold"></i> Wax-potted</li>
                <li><i class="fa fa-check-square-o specs-gold"></i> Overwound on request</li>

            </ul>
        </div>
        <p>&nbsp;</p>
        <p class="description text-90"><?=SBCustom\CommonStrings::text('pickups_description_box')?></p>
        <div class="addthis_inline_share_toolbox top-20"></div>
        <a href="mailto:info@sbcustom.pt?subject=Vintage P-Bass Info" class="btn"><i class="fa fa-envelope"></i>
            info</a>
    </div>
</div>