<div class="clearfix">
    <h2 class="small-heading" id="stratocaster-set">STRATOCASTER<sup>&trade;</sup> SETS</h2>
    <div class="row">
        <div class="col-md-10 col-md-offset-1 col-xs-10 col-xs-offset-1">
            <div class="row">
                <div class="col-md-6 price-category-gold">
                    <div class="price-box">
                        <p class="set-name">Vintage 54 "Surf"</p>
                        <p><span class="price"></span></p>
                        <p class="description">This are the pickups that shape the sound of the Stratocaster<sup>&trade;</sup>.
                            Many guitarist, still prefer this early sound. Known better as the "Surf Tone".
                            Sparkle highs and mids, fattening up when you push hard.
                            Ideal for clean and mild overdrive.</p>
                        <div class="col-md-6">
                            <ul style="text-align: left;">
                                <li><i class="fa fa-check-square-o specs-gold"></i> Vintage correct vulcanized fiber work</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> 0.195" Alnico 3 vintage bevel top polepiece magnets</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> E: 0.671"  A: 0.671"  D: 0.710"</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> G: 0.671"  B: 0.630"  E: 0.650"</li>

                            </ul>
                        </div>
                        <div class="col-md-6" style="padding-bottom: 20px">
                            <ul style="text-align: left">
                                <li><i class="fa fa-check-square-o specs-gold"></i> Middle Pickup is RW/RP</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Vintage style push-back wire</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> 42 AWG Heavy Formvar Wire</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> DC Resistance: ~ 5.8 K</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Wax-potted</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Overwound on request</li>
                            </ul>
                        </div>

                        <p class="description text-90">Like all SB Custom pickups these are shipped in a premium product box, and come with all mounting hardware and a wiring diagram.</p>

                        <a href="mailto:info@sbcustom.pt?subject=Vintage 54 Set Info" class="btn"><i class="fa fa-envelope"></i> info</a>
                    </div>


                </div>
                <div class="col-md-6 price-category-gold">
                    <div class="price-box">
                        <p class="set-name">Vintage 59 "Sweet"</p>
                        <p><span class="price"></span></p>
                        <p class="description">The first evolution of the single coils. Now with Alnico 5 magnets, it delivers a fat "Sweet" punchy tone.
                            With smooth mids, it cleans up nicely when the volume is rolled back.
                            Great for clean and low to medium overdrive.</p>
                        <div class="col-md-6">
                            <ul style="text-align: left;">
                                <li><i class="fa fa-check-square-o specs-gold"></i> Vintage correct vulcanized fiber work</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> 0.195" Alnico 5 vintage bevel top polepiece magnets</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> E: 0.671"  A: 0.671"  D: 0.710"</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> G: 0.671"  B: 0.630"  E: 0.650"</li>

                            </ul>
                        </div>
                        <div class="col-md-6" style="padding-bottom: 20px">
                            <ul style="text-align: left">
                                <li><i class="fa fa-check-square-o specs-gold"></i> Middle Pickup is RW/RP</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Vintage style push-back wire</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> 42 AWG Natural Enamel Wire</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> DC Resistance: ~ 5.8K - 6.0K</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Wax-potted</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Overwound on request</li>
                            </ul>
                        </div>
                        <p class="description text-90">Like all SB Custom pickups these are shipped in a premium product box, and come with all mounting hardware and a wiring diagram.</p>
                        <a href="mailto:info@sbcustom.pt?subject=Vintage 59 Set Info" class="btn"><i class="fa fa-envelope"></i> info</a>
                    </div>
                </div>
                <div class="col-md-6 price-category-gold">
                    <div class="price-box">
                        <p class="set-name">Vintage 65 "Blues Deluxe"</p>
                        <p><span class="price"></span></p>
                        <p class="description">This is our "hottest" set. Much like the 59, but slightly overwound and different wire, this pickups unleash full Blues Tones.
                            They drive a clean amp, to the verge of breakup, giving that full "punchy" sound.
                            Great for clean and low to medium overdrive.</p>
                        <div class="col-md-6">
                            <ul style="text-align: left;">
                                <li><i class="fa fa-check-square-o specs-gold"></i> Vintage correct vulcanized fiber work</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> 0.195" Alnico 5 vintage bevel top polepiece magnets</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> E: 0.671"  A: 0.671"  D: 0.710"</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> G: 0.671"  B: 0.630"  E: 0.650"</li>

                            </ul>
                        </div>
                        <div class="col-md-6" style="padding-bottom: 20px">
                            <ul style="text-align: left">
                                <li><i class="fa fa-check-square-o specs-gold"></i> Middle Pickup is RW/RP</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Vintage style push-back wire</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> 42 AWG Heavy Formvar Wire</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> DC Resistance: ~ 6.0K - 6.4K</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Wax-potted</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Overwound on request</li>
                            </ul>
                        </div>

                        <p class="description text-90">Like all SB Custom pickups these are shipped in a premium product box, and come with all mounting hardware and a wiring diagram.</p>
                        <a href="mailto:info@sbcustom.pt?subject=Vintage 65 Set Info" class="btn"><i class="fa fa-envelope"></i> info</a>
                    </div>
                </div>
                <div class="col-md-6 price-category-gold">
                    <div class="price-box">
                        <p class="set-name">Vintage 69 "Haze"</p>
                        <p><span class="price"></span></p>
                        <p class="description">The late 60's sound is undoubtedly connected to the great Jimi Hendrix.
                            This set recreates that amazing sound, that we learn to love.
                            Using different type of wire and magnets size, it delivers that rich full tone.
                            Clean and low to medium overdrive.</p>
                        <div class="col-md-6">
                            <ul style="text-align: left;">
                                <li><i class="fa fa-check-square-o specs-gold"></i> Vintage correct vulcanized fiber work</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> 0.187" Alnico 5 vintage bevel top polepiece magnets</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> E: 0.671"  A: 0.671"  D: 0.710"</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> G: 0.671"  B: 0.630"  E: 0.650"</li>

                            </ul>
                        </div>
                        <div class="col-md-6" style="padding-bottom: 20px">
                            <ul style="text-align: left">
                                <li><i class="fa fa-check-square-o specs-gold"></i> Middle Pickup is RW/RP</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Vintage style push-back wire</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> 42 AWG Plain Enamel Wire</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> DC Resistance: ~ 5.8K - 6.0K</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Wax-potted</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Overwound on request</li>
                            </ul>
                        </div>

                        <p class="description text-90">Like all SB Custom pickups these are shipped in a premium product box, and come with all mounting hardware and a wiring diagram.</p>
                        <a href="mailto:info@sbcustom.pt?subject=Vintage 69 Set Info" class="btn"><i class="fa fa-envelope"></i> info</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>