<div class="clearfix">
    <h2 class="small-heading" id="telecaster-set">TELECASTER<sup>&trade;</sup> SETS</h2>
    <div class="row">
        <div class="col-md-10 col-md-offset-1 col-xs-10 col-xs-offset-1">
            <div class="row">
                <div class="col-md-6 price-category-gold">
                    <div class="price-box">
                        <p class="set-name">50s Vintage Blackguard Telecaster<sup>&trade;</sup></p>
                        <p><span class="price"></span></p>
                        <p class="description">The Telecaster<sup>&trade;</sup> was the first real production electric guitar. This pickups will give you the unmistakable twang, that is still a favourite amongst several guitar players.
                            With a warmer, fatter in the bridge and clear bright tone on the neck, this set is the perfect replacement for your guitar.</p>
                        <div class="col-md-6">
                            <p class="gold">Bridge Pickup</p>
                            <ul style="text-align: left;">
                                <li><i class="fa fa-check-square-o specs-gold"></i> Vintage correct vulcanized fiber work</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> 0.187" Alnico 3 Flush mounted Alnico sand cast polepiece magnets</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> E: 0.630"  A: 0.630"  D: 0.630"</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> G: 0.630"  B: 0.630"  E: 0.630"</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Copper clad steel bridge pickup plate</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> 42 AWG Plain Enamel Wire</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> DC Resistance: ~ 7K</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Wax-potted</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Overwound on request</li>

                            </ul>
                        </div>
                        <div class="col-md-6" style="padding-bottom: 20px">
                            <p class="gold">Neck Pickup</p>
                            <ul style="text-align: left">
                                <li><i class="fa fa-check-square-o specs-gold"></i> Vintage correct vulcanized fiber work</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> 0.187" Alnico 3 Flush mounted Alnico sand cast polepiece magnets.</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> E: 0.671"  A: 0.671"  D: 0.671"</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> G: 0.671"  B: 0.671"  E: 0.671"</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> 43 AWG Plain Enamel Wire</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> DC Resistance: ~ 7,3K</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Wax-potted</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Overwound on request</li>
                            </ul>
                        </div>
                        <p>&nbsp;</p>
                        <p class="description text-90"><?=SBCustom\CommonStrings::text('pickups_description_box')?></p>
                        <div class="addthis_inline_share_toolbox top-20"></div>
                        <a href="mailto:info@sbcustom.pt?subject=50s Vintage Blackguard Telecaster Info" class="btn"><i class="fa fa-envelope"></i> info</a>
                    </div>


                </div>
                <div class="col-md-6 price-category-gold">
                    <div class="price-box">
                        <p class="set-name">Tele<sup>&reg;</sup> Junkie</p>
                        <p><span class="price"></span></p>
                        <p class="description">This is a set for tone junkies. With a mix of Alnico 2 on the 3 high strings, and Alnico 5 on the bottom 3, this combination produces a smooth yet punchy, well response bass tone.
                            Tele<sup>&reg;</sup> classic with a twist.</p>
                        <div class="col-md-6">
                            <p class="gold">Bridge Pickup</p>
                            <ul style="text-align: left;">
                                <li><i class="fa fa-check-square-o specs-gold"></i> Vintage correct vulcanized fiber work</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> 0.187" Alnico V sand cast polepiece magnets on the low E, A, D strings</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> 0.187" Alnico II sand cast polepiece magnets on the high G, B, E strings</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> E: 0.630"  A: 0.630"  D: 0.630"</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> G: 0.630"  B: 0.630"  E: 0.630"</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Copper clad steel bridge pickup plate</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> 42 AWG Natural Enamel Wire</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> DC Resistance: ~ 7K</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Wax-potted</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Overwound on request</li>
                            </ul>
                        </div>
                        <div class="col-md-6" style="padding-bottom: 20px">
                            <p class="gold">Neck Pickup</p>
                            <ul style="text-align: left">
                                <li><i class="fa fa-check-square-o specs-gold"></i> Vintage correct vulcanized fiber work</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> 0.187" Alnico V sand cast polepiece magnets on the low E, A, D strings</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> 0.187" Alnico II sand cast polepiece magnets on the high G, B, E strings</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> E: 0.671"  A: 0.671"  D: 0.671"</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> G: 0.671"  B: 0.671"  E: 0.671"</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> 43 AWG Plain Enamel Wire</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> DC Resistance: ~ 7,3K</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Wax-potted</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Overwound on request</li>
                            </ul>
                        </div>
                        <p>&nbsp;</p>

                        <p class="description text-90"><?=SBCustom\CommonStrings::text('pickups_description_box')?></p>
                        <div class="addthis_inline_share_toolbox top-20"></div>
                        <a href="mailto:info@sbcustom.pt?subject=Tele Junkie Info" class="btn"><i class="fa fa-envelope"></i> info</a>
                    </div>
                </div>
                <div class="col-md-6 price-category-gold">
                    <div class="price-box">
                        <p class="set-name">Bluesy M Series Telecaster<sup>&trade;</sup></p>
                        <p><span class="price"></span></p>
                        <p class="description">This set is for the modern player. Without compromise the classic Tele<sup>&reg;</sup> sound, the Alnico 5 magnets, deliver a sweet but powerfull sound.
                            Slightly overwound, for a rich fat tone.</p>
                        <div class="col-md-6">
                            <p class="gold">Bridge Pickup</p>
                            <ul style="text-align: left;">
                                <li><i class="fa fa-check-square-o specs-gold"></i> Vintage correct vulcanized fiber work</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> 0.195" Alnico 3 Flush mounted Alnico sand cast polepiece magnets</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> E: 0.630"  A: 0.630"  D: 0.630"</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> G: 0.630"  B: 0.630"  E: 0.630"</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Copper clad steel bridge pickup plate</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> 42 AWG Natural Enamel Wire</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> DC Resistance: ~ 7,5K</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Wax-potted</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Overwound on request</li>
                            </ul>
                        </div>
                        <div class="col-md-6" style="padding-bottom: 20px">
                            <p class="gold">Neck Pickup</p>
                            <ul style="text-align: left">
                                <li><i class="fa fa-check-square-o specs-gold"></i> Vintage correct vulcanized fiber work</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> 0.195" Alnico 3 Flush mounted Alnico sand cast polepiece magnets.</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> E: 0.671"  A: 0.671"  D: 0.671"</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> G: 0.671"  B: 0.671"  E: 0.671"</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> 43 AWG Plain Enamel Wire</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> DC Resistance: ~ 7,8K</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Wax-potted</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Overwound on request</li>
                            </ul>
                        </div>
                        <p>&nbsp;</p>
                        <p class="description text-90"><?=SBCustom\CommonStrings::text('pickups_description_box')?></p>
                        <div class="addthis_inline_share_toolbox top-20"></div>
                        <a href="mailto:info@sbcustom.pt?subject=Bluesy M Series Telecaster Info" class="btn"><i class="fa fa-envelope"></i> info</a>
                    </div>
                </div>
                <div class="col-md-6 price-category-gold">
                    <div class="price-box">
                        <p class="set-name">Li'l Twister - André Rodrigues Signature Series</p>
                        <p><span class="price"></span></p>
                        <p class="description">Built in close partnership with the talented guitarist André Rodrigues, this set was designed with versatility in mind. The open style cover in the neck pickup give it a sparkle that normally Telecasters do not have.The bridge pickup is a real treaty. With a tap coil, we can have the best of two worlds, a wonderful vintage sound, but when engage the second wire we have a great roar, excelent for a good rock & roll.</p>
                        <div class="col-md-6">
                            <p class="gold">Bridge Pickup</p>
                            <ul style="text-align: left;">
                                <li><i class="fa fa-check-square-o specs-gold"></i> Vintage correct vulcanized fiber work</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> 0.195" Alnico 3 Flush mounted Alnico sand cast polepiece magnets</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> E: 0.671"  A: 0.671"  D: 0.671"</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> G: 0.671"  B: 0.671"  E: 0.671"</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Copper clad steel bridge pickup plate</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> 42 AWG Heavy Formvar Wire</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> 43 AWG Plain Enamel Wire</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Coil Tap</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> DC Resistance: ~ 11,3K</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Wax-potted</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Overwound on request</li>
                            </ul>
                        </div>
                        <div class="col-md-6" style="padding-bottom: 20px">
                            <p class="gold">Neck Pickup</p>
                            <ul style="text-align: left">
                                <li><i class="fa fa-check-square-o specs-gold"></i> Vintage correct vulcanized fiber work</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> 0.195" Alnico 3 Flush mounted Alnico sand cast polepiece magnets.</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> E: 0.688"  A: 0.688"  D: 0.688"</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> G: 0.688"  B: 0.688"  E: 0.688"</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> 43 AWG Plain Enamel Wire</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Open Style Cover</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> DC Resistance: ~ 7,3K</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Wax-potted</li>
                                <li><i class="fa fa-check-square-o specs-gold"></i> Overwound on request</li>
                            </ul>
                        </div>
                        <p>&nbsp;</p>
                        <p>&nbsp;</p>
                        <p class="description text-90"><?=SBCustom\CommonStrings::text('pickups_description_box')?></p>
                        <div class="addthis_inline_share_toolbox top-20"></div>
                        <a href="mailto:info@sbcustom.pt?subject=Li'l Twister - André Rodrigues Signature Series Info" class="btn"><i class="fa fa-envelope"></i> info</a>
                        <a href="https://www.facebook.com/MrJackGuitars/videos/1081253588612659/" target="_blank" class="btn"><i class="fa fa-video-camera"></i> video</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>